version: "2.3"
services:
  app:
    build:
      context: ./src
      #dockerfile: Dockerfile.Staged
      dockerfile: Dockerfile.Test
      #target: tester
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app