# first stage
FROM golang:1.13-alpine3.11 AS builder
RUN apk add git bash
ENV GO111MODULE=on
ENV GOPROXY=direct
EXPOSE 8080
WORKDIR /app
ADD . .
RUN go build -i -o /bin/api main.go

# final stage
FROM alpine:3.11
COPY --from=builder /bin/api /bin/
CMD [ "/bin/api" ]